#!/bin/bash

# Manual Web App Testing Checklist
# Run this to verify the web app is working

echo "🧪 Manual Web App Testing Checklist"
echo "===================================="
echo ""
echo "Web app URL: http://localhost:8000"
echo ""
echo "✅ Test Cases:"
echo ""
echo "1. Page Load:"
echo "   - Open http://localhost:8000"
echo "   - Should see 'Age of Sigmar Damage Calculator'"
echo "   - Chart should be visible"
echo ""
echo "2. Fixed Values:"
echo "   - Attacks: 10 (fixed)"
echo "   - To Hit: 3+"
echo "   - To Wound: 3+"
echo "   - Rend: 1"
echo "   - Damage: 1 (fixed)"
echo "   - Save: 4+"
echo "   - Expected mean: ~2.96"
echo ""
echo "3. Dice Notation:"
echo "   - Change Attacks dropdown to 'D6'"
echo "   - N and M sliders should hide"
echo "   - Notation display: 'D6'"
echo "   - Mean damage should update"
echo ""
echo "4. Compound Dice (ND6+M):"
echo "   - Attacks dropdown: 'ND6+M'"
echo "   - N slider appears (set to 2)"
echo "   - M slider appears (set to 3)"
echo "   - Notation display: '2D6+3'"
echo "   - Mean damage should be higher"
echo ""
echo "5. Hit Rules:"
echo "   - Try all hit rules: normal, crit_auto_wound, crit_mortal_wound, crit_double_hit"
echo "   - Crit rules should always show higher mean damage"
echo ""
echo "6. Ward Saves:"
echo "   - Change Ward slider from 'None' to 5+"
echo "   - Mean damage should decrease"
echo ""
echo "7. Label Consistency:"
echo "   - When 'Fixed Value' selected: label shows 'Value:'"
echo "   - When 'ND6+M' selected: label shows 'N (multiplier):'"
echo ""
echo "8. Initial State:"
echo "   - Refresh page"
echo "   - Attacks should show only N slider (value 10)"
echo "   - Damage should show only N slider (value 1)"
echo "   - M sliders should be hidden"
echo ""

# Quick smoke test via curl
if curl -s http://localhost:8000 | grep -q "Age of Sigmar"; then
    echo "✅ Web server is running and page loads"
else
    echo "❌ Web server may not be running or page has issues"
fi
